### ISSUE TITLE
Problem with plugins

### ISSUE THREAD

**Issue by tatidealencar** [creativetimofficial/impact-design-system#8]
I'm trying to use the Datepicker plugin, following this tutorial: https://demos.creative-tim.com/impact-design-system-pro/docs/plugins/datepicker/, but it didn't work. 

On the HTML page I added the code snippet below:
`<div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="ni ni-calendar-grid-58"></i></span>
                        </div>
                        <input class="form-control datepicker" placeholder="Select date" type="text" value="06/20/2020">
                    </div>
                </div>`

On the _scripts.html page I added the code snippet below:

`<script src="/assets/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
`

To test it, I tried to use other puglins available in the free version, and they didn't work either.

Is there any problem with the plugins available in the template?

Thanks.

**Comment by zoltanszogyenyi** [comment]
@tatidealencar are you sure the path is correct to plugin? Please check your console log.

**Comment by zoltanszogyenyi** [comment]
@tatidealencar any news on this? Did you manage to get it working?

**Comment by zoltanszogyenyi** [comment]
Closed, unless @tatidealencar comes back with clarification whether she resolved the problem or not :)
